I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 216, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 531, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 531, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 542, in _execute_python_hide
    renpy.load(renpy.session["_reload_slot"])
FileNotFoundError: [Errno 2] No such file or directory: '/Users/muzz/Library/RenPy/RightsAQuest-1708695731/sync/_reload-1-LT1.save'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 216, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 531, in script
    python hide:
  File "/Applications/renpy-8.2.0-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-8.2.0-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 531, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 542, in _execute_python_hide
    renpy.load(renpy.session["_reload_slot"])
  File "/Applications/renpy-8.2.0-sdk/renpy/loadsave.py", line 823, in load
    log_data, signature = location.load(filename)
  File "/Applications/renpy-8.2.0-sdk/renpy/savelocation.py", line 532, in load
    return l.load(slotname) # type: ignore
  File "/Applications/renpy-8.2.0-sdk/renpy/savelocation.py", line 284, in load
    with zipfile.ZipFile(filename, "r") as zf:
  File "lib/python3.9/zipfile.py", line 1239, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/muzz/Library/RenPy/RightsAQuest-1708695731/sync/_reload-1-LT1.save'

macOS-14.1.1-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
RightsAQuest 1.0
Sat Feb 24 13:05:56 2024
